# Generated by Django 5.0.4 on 2024-05-05 22:58

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lexiconverbentry',
            name='iguwot',
            field=models.CharField(blank=True, max_length=25, null=True, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['IGNORECASE'], message='You must only use letters in the Kovol orthography', regex='^[ieauowtyplkhgdsbnm]+$')], verbose_name='-ogot suffix'),
        ),
        migrations.AddField(
            model_name='lexiconverbentry',
            name='iguwot_checked',
            field=models.BooleanField(default=False),
        ),
    ]
