# Generated by Django 5.0.4 on 2024-05-05 23:07

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0002_lexiconverbentry_iguwot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kovolwordsense',
            name='sense',
            field=models.CharField(help_text='write the English for the additional sense here', max_length=45, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['IGNORECASE'], message='You cannot put symbols here', regex="^[a-z /d']+$")], verbose_name='sense'),
        ),
        migrations.AlterField(
            model_name='lexiconentry',
            name='eng',
            field=models.CharField(max_length=45, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['IGNORECASE'], message='You cannot put symbols here', regex="^[a-z /d']+$")], verbose_name='English'),
        ),
        migrations.AlterField(
            model_name='lexiconverbentry',
            name='iguwot_checked',
            field=models.BooleanField(default=False, verbose_name='-ogot checked'),
        ),
        migrations.AlterField(
            model_name='phrasesense',
            name='sense',
            field=models.CharField(help_text='write the English for the additional sense here', max_length=45, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['IGNORECASE'], message='You cannot put symbols here', regex="^[a-z /d']+$")], verbose_name='sense'),
        ),
        migrations.AlterField(
            model_name='verbsense',
            name='sense',
            field=models.CharField(blank=True, help_text='The English for an additional sense to a verb', max_length=45, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['IGNORECASE'], message='You cannot put symbols here', regex="^[a-z /d']+$")], verbose_name='Sense'),
        ),
    ]
