# Generated by Django 5.0.4 on 2024-07-18 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0003_alter_kovolwordsense_sense_alter_lexiconentry_eng_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LexiconMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.DecimalField(decimal_places=3, default=0.0, max_digits=5, verbose_name='version')),
            ],
        ),
    ]
