# Generated by Django 5.0.4 on 2024-08-19 00:00

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0004_lexiconmetadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgnoreWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(help_text='Word to add to spell check.', max_length=25, unique=True)),
                ('type', models.CharField(choices=[('tpi', 'Tok Pisin'), ('pn', 'Proper noun'), ('eng', 'English'), ('fgn', 'Foreign transliterated')], help_text='Type of word to add to spell check.', max_length=3)),
                ('eng', models.CharField(help_text='English', max_length=25, verbose_name='English')),
                ('comments', models.TextField(blank=True, help_text='extra comments or an extended definition information', max_length=300, null=True)),
            ],
            options={
                'ordering': ['word'],
            },
        ),
        migrations.AlterField(
            model_name='kovolword',
            name='matat',
            field=models.CharField(blank=True, max_length=45, null=True, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['IGNORECASE'], message='You must only use letters in the Kovol orthography', regex='^[ieauoəwtyplkhgdsbnmz ]+$')], verbose_name='Matat'),
        ),
        migrations.AlterField(
            model_name='lexiconentry',
            name='comments',
            field=models.TextField(blank=True, help_text='extra comments or an extended definition information', max_length=1000, null=True),
        ),
    ]
