# Generated by Django 2.2.8 on 2020-01-02 01:41

import CE.models
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='CultureEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('description_plain_text', models.TextField(blank=True)),
                ('differences', models.TextField(blank=True)),
                ('interpretation', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_present', models.CharField(blank=True, max_length=60)),
                ('nationals_present', models.CharField(blank=True, max_length=60)),
                ('date', models.DateField(blank=True, null=True)),
                ('ce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CE.CultureEvent')),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_title', models.CharField(blank=True, max_length=50)),
                ('audio', models.FileField(blank=True, upload_to=CE.models.audio_folder)),
                ('phonetic_text', models.TextField(blank=True)),
                ('phonetic_standard', models.CharField(blank=True, choices=[('1', 'Unchecked'), ('2', 'Double checked by author'), ('3', 'Checked by team mate'), ('4', 'Approved by whole team'), ('5', 'Valid for linguistic analysis')], default='1', max_length=30)),
                ('orthographic_text', models.TextField(blank=True)),
                ('discourse_type', models.CharField(blank=True, choices=[('1', 'Narrative'), ('2', 'Hortatory'), ('3', 'Procedural'), ('4', 'Expository'), ('5', 'Descriptive')], max_length=15)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.CharField(blank=True, max_length=20)),
                ('ce', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CE.CultureEvent')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.CharField(blank=True, max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('asked_by', models.CharField(max_length=30)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.CharField(max_length=20)),
                ('answered_by', models.CharField(max_length=20)),
                ('ce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CE.CultureEvent')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to=CE.models.picture_folder)),
                ('ce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CE.CultureEvent')),
            ],
        ),
    ]
