# Generated by Django 2.2.6 on 2019-12-07 05:16

from django.db import migrations
from CE import models

def insert_example_CEs(apps, schema_editor):
    example_ce_1 = models.CultureEvent(
        title="Example CE",
        last_modified_by='CLAHubDev',
        description_plain_text='''We arranged with a family beforehand that we'd come with the and see how laundry is done.
The family was waiting for us when we arrived, they had remembered we were coming.
The children were sent by some ladies to get some buckets and 2 girls went to get water from the public well.
We went to an area that had a big piece of hard plastic that lying on a big tractor tire. 
One girl first made all the clothes wet in one bucket and transferred them to another bucket. Another girl put soap in this bucket and made the water soapy. Then she took out the clothes one by one, laid them on the plastic and brushed them with a brush. Clothes with stains were treated with bleach and put aside to soak for a couple of minutes. Fragile clothes were kneaded together with soap and not brushed. 
In between someone had gotten 2 more buckets of water.
One was to rinse off the soap. Then the second one to rinse again.
The wet clothes were put in another bucket again and hung up at the washing line.''',
    interpretation='''There were no men present at all suggesting that laundry is women's work.''',
    differences='I\'ve seen people washing at a nearby stream too'
    )
    example_ce_1.save()
    example_text_1 = models.Text(
        ce=example_ce_1,
        text_title='Maryanne talking about doing laundry',
        phonetic_text='''oke fəst mipla ɡo pulapim wara kam kapsaⁱtim insaⁱt lo bakɛt sɛrim wara biloŋ 
        raᵘsim dəti lo rins na mipla fəst mipla wasim dəti bihaⁱn mipla putim ɡo lo sop wara mipla 
        brasim ol klots pinis sampla blo blits ja mipla blitsim ol pinis mipla putim go lo rins wara 
        mipla rinsim rinsim sop raᵘsim mipla ɡo lo klin wara mipla rinsim naᵘ mipla ɡo haŋgamapim lo 
        laⁱn ɛm tʃol''',
        phonetic_standard='1',
        discourse_type='3',
        last_modified_by='CLAHubDev',
        orthographic_text='''Orthographic text goes here :)''',
        audio='example_data/example_audio1.mp3'
)
    example_text_1.save()
    example_ce_1.tags.add('Example')

    example_pic1 = models.Picture(picture='example_data/example_CE_pic1.jpg',
                                  ce=example_ce_1)
    example_pic1.save()
    example_pic2 = models.Picture(picture='example_data/example_CE_pic2.jpg',
                                  ce=example_ce_1)
    example_pic2.save()
    example_pic3 = models.Picture(picture='example_data/example_CE_pic3.jpg',
                                  ce=example_ce_1)
    example_pic3.save()
    example_pic4 = models.Picture(picture='example_data/example_CE_pic4.jpg',
                                  ce=example_ce_1)
    example_pic4.save()

    visit = models.Visit(ce=example_ce_1,
                         team_present='Gerdine, Becky',
                         nationals_present='Maryanne and family',
                         date='2016-02-06')
    visit.save()
    question1 = models.Question(ce=example_ce_1,
                                asked_by='CLAHubDev',
                                last_modified_by='CLAHubDev',
                                question='Do some families struggle to afford soap, or does everyone have it?')
    question1.save()
    question2 = models.Question(ce=example_ce_1,
                                asked_by='CLAHubDev',
                                last_modified_by='CLAHubDev',
                                question='How dirty do people let their clothes get before washing?',
                                answer='Pretty dirty :), but they do take more care to not get them so dirty in the first place compared to us.'
                                )
    question2.save()

    example_ce_2 = models.CultureEvent(
        title='Explanation of CLAHub features',
        last_modified_by='CLAHubDev',
        description_plain_text='''This area is for describing the Culture Event (CE) in general. The
         description field should contain objective information (no interpretation, guesses,
          musings or language learner POV) about the CE.Your
        team should work together to build a complete page for each CE. The intention of CLAHub is that
        pages become a snapshot of the team's best information on any given CE. That means there will
        be a single \'Harvesting Sago\' CE that team members add information to over time. There
        shouldn\'t be \'Team member A goes fishing\' and \'Team member B goes fishing\' CEs, but
        rather if team member A creates a Fishing CE, team member B should build on it.
         
         Language learning will require that both team member A and team member B both have personalised
         notes elsewhere. For instance team member A might be working on learning basic vocabulary,
          but Team member B is further along and is working on learning something else. CLAHub isn\'t 
          designed to file those notes and they should be kept separately by each language learner so
          they can learn as productively as possible
          
          The description field is unique in CLAHub in that it will automatically create cross
          references between CEs by simply reading the text. All you need to do to create a link
          to anther CE is to type it's title. example ce for example.''',
        interpretation='''Typically a CE has much more going on than what can be documented on
        a surface level. This field is a place where you can write up implicit information about a 
        CE. As a language learner you're likely to guess wrong at times and interpret CEs incorrectly,
        this is why the deescription is to remain objective. This field allows the team to dig deeper,
        while keeping objective facts separate from the team's understanding of a culture's worldview''',
        differences='Multiple team members will be contributing to each CE and team members will'
                    'participate in CEs multiple times. The description field allows the team to write'
                    'a generalized description of the CE, while the variations field allows team members'
                    'to include information about times the CE deviated from the regular pattern, or to'
                    'add specific information from their participation'
    )
    example_ce_2.save()

class Migration(migrations.Migration):
    dependencies = [
        ('CE', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_example_CEs)
    ]
