# Generated by Django 2.2.8 on 2020-01-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('village', models.CharField(choices=[('1', 'Elilim'), ('2', 'Evesil'), ('3', 'Kobumbua'), ('4', 'Kokoma'), ('5', 'Magilong'), ('6', 'Pusilai'), ('7', 'Torokum')], max_length=60)),
                ('picture', models.ImageField(blank=True, upload_to='people/profile_pictures')),
                ('clan', models.CharField(blank=True, max_length=60)),
                ('born', models.DateField(blank=True, null=True)),
                ('dialect', models.CharField(blank=True, max_length=60)),
                ('death', models.DateField(blank=True, null=True)),
                ('family_plain_text', models.TextField(blank=True)),
                ('family', models.TextField(blank=True)),
                ('medical', models.TextField(blank=True)),
                ('team_contact', models.TextField(blank=True)),
                ('education', models.CharField(blank=True, choices=[('1', 'None'), ('2', 'Grade 1'), ('3', 'Grade 2'), ('4', 'Grade 4'), ('5', 'Grade 10')], max_length=60)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.CharField(max_length=20)),
                ('thumbnail', models.ImageField(blank=True, upload_to='people/thumbnails')),
            ],
        ),
    ]
