# Generated by Django 3.1.6 on 2021-02-19 11:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('picture', models.ImageField(blank=True, upload_to='people/profile_pictures')),
                ('clan', models.CharField(blank=True, max_length=60)),
                ('born', models.DateField(blank=True, null=True)),
                ('originally_from', models.CharField(blank=True, max_length=60)),
                ('death', models.DateField(blank=True, null=True)),
                ('family_plain_text', models.TextField(blank=True)),
                ('family', models.TextField(blank=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('medical', models.TextField(blank=True)),
                ('team_contact', models.TextField(blank=True)),
                ('education', models.CharField(blank=True, choices=[('1', 'None'), ('2', 'Grade 1'), ('3', 'Grade 2'), ('4', 'Grade 4'), ('5', 'Grade 10')], max_length=60)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.CharField(max_length=20)),
                ('thumbnail', models.ImageField(blank=True, upload_to='people/thumbnails')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.village')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjective', models.TextField()),
                ('objective', models.TextField()),
                ('assessment', models.TextField()),
                ('plan', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('short', models.CharField(max_length=25)),
                ('image', models.ImageField(blank=True, upload_to='people/medical')),
                ('comment', models.TextField(blank=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.person')),
            ],
        ),
    ]
