# Generated by Django 3.1.1 on 2020-10-12 04:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_medicalassessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalassessment',
            name='date',
            field=models.DateField(default=datetime.date(2020, 10, 12)),
        ),
    ]
