# Generated by Django 3.1.6 on 2021-02-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_auto_20201012_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='village',
            field=models.CharField(blank=True, choices=[('1', 'Elilim'), ('2', 'Evesil'), ('3', 'Kobumbua'), ('4', 'Kokoma'), ('5', 'Magilong'), ('6', 'Pusilai'), ('7', 'Torokum')], max_length=60, null=True),
        ),
    ]
