# Generated by Django 3.1.6 on 2021-02-19 10:28

from django.db import migrations


def fill_village(apps, schema_editor):
    village_names = {
        '1': 'Elilim',
        '2': 'Evesil',
        '3': 'Kobumbua',
        '4': 'Kokoma',
        '5': 'Magilong',
        '6': 'Pusilai',
        '7': 'Torokum'
    }
    Person = apps.get_model('people', 'Person')
    Village = apps.get_model('people', 'Village')
    for person in Person.objects.all():
        village, created = Village.objects.get_or_create(village_name=village_names[person.village])
        person.temp_village = village
        person.save()


class Migration(migrations.Migration):
    dependencies = [
        ('people', '0008_person_temp_village'),
    ]

    operations = [migrations.RunPython(fill_village)
                  ]
