# Generated by Django 3.1.6 on 2021-02-19 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_populate_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='village',
        ),
    ]
