# Generated by Django 3.1.6 on 2021-02-19 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_remove_person_village'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='temp_village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.village'),
        ),
    ]
