# Generated by Django 3.1.6 on 2021-02-19 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_auto_20210219_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='temp_village',
            new_name='village',
        ),
    ]
