# Generated by Django 4.1.5 on 2023-07-06 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0012_auto_20210219_2048"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="village",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="people.village",
            ),
        ),
    ]
